#!/usr/bin/env python
"""Gradio data-collection studio for recording Hindi TTS speech data.

Generates batches of Hindi sentences from a local Ollama model, then lets
you record yourself reading each one with your microphone. Saves paired
files into data/raw/hindi/ as NNN.txt + NNN.wav, matching the layout
datasets/hindi/loader.py and scripts/tokenize_dataset.py expect.

Launch:
  python scripts/record_studio.py

Then open http://localhost:7861 in a browser.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import gradio as gr
import soundfile as sf

from preprocessing.text.hindi_sentence_generator import DEFAULT_MODEL, generate_batch

DEFAULT_OUTPUT_DIR = Path("data/raw/hindi")


def next_index(output_dir: Path) -> int:
    existing = [int(p.stem) for p in output_dir.glob("*.txt") if p.stem.isdigit()]
    return max(existing, default=0) + 1


def save_pair(output_dir: Path, index: int, text: str, audio_path: str) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"{index:03d}"
    txt_path = output_dir / f"{stem}.txt"
    wav_path = output_dir / f"{stem}.wav"

    txt_path.write_text(text.strip() + "\n", encoding="utf-8")

    src = Path(audio_path)
    if src.suffix.lower() == ".wav":
        shutil.copy(src, wav_path)
    else:
        data, sr = sf.read(str(src), dtype="float32")
        sf.write(wav_path, data, sr)
    return wav_path


def describe(sentences: list[str], position: int, next_idx: int) -> tuple[str, str, str]:
    """Returns (sentence_text, save_as_filename, progress_text) for the current position."""
    total = len(sentences)
    if total == 0:
        return "", "", "No batch generated yet — click \"Generate new batch\"."
    if position >= total:
        return "", "", "Batch complete — click \"Generate new batch\" for more sentences."
    stem = f"{next_idx:03d}"
    return sentences[position], f"{stem}.wav / {stem}.txt", f"Sentence {position + 1} of {total}"


def build_app(model: str, batch_size: int, output_dir: Path) -> gr.Blocks:
    start_idx = next_index(output_dir)

    with gr.Blocks(title="Hindi TTS Recording Studio") as demo:
        gr.Markdown("## Hindi TTS Recording Studio")
        gr.Markdown(
            f"Sentences generated by `{model}` via Ollama. "
            f"Recordings saved to `{output_dir}/` as `NNN.wav` + `NNN.txt`."
        )

        sentences_state = gr.State([])
        position_state = gr.State(0)
        next_idx_state = gr.State(start_idx)

        with gr.Row():
            saved_count = gr.Textbox(label="Saved so far", value=str(start_idx - 1), interactive=False)
            batch_progress = gr.Textbox(label="Batch progress", value="No batch generated yet", interactive=False)

        sentence_box = gr.Textbox(label="Read this sentence aloud", lines=3, interactive=False)
        next_file_box = gr.Textbox(label="Will save as", interactive=False)

        generate_btn = gr.Button("Generate new batch of sentences", variant="primary")

        audio_in = gr.Audio(sources=["microphone"], type="filepath", label="Record your voice")

        with gr.Row():
            save_btn = gr.Button("Save & Next", variant="primary")
            skip_btn = gr.Button("Skip sentence (don't save)")

        status_box = gr.Textbox(label="Status", interactive=False)

        def on_generate(next_idx):
            try:
                batch = generate_batch(n=batch_size, model=model)
            except RuntimeError as e:
                return [], 0, next_idx, "", "", "No batch generated yet", str(next_idx - 1), str(e)
            if not batch:
                msg = "LLM returned no usable Hindi sentences — try again."
                return [], 0, next_idx, "", "", "No batch generated yet", str(next_idx - 1), msg
            sentence, filename, progress = describe(batch, 0, next_idx)
            status = f"Generated {len(batch)} sentences."
            return batch, 0, next_idx, sentence, filename, progress, str(next_idx - 1), status

        generate_btn.click(
            on_generate,
            inputs=[next_idx_state],
            outputs=[
                sentences_state, position_state, next_idx_state,
                sentence_box, next_file_box, batch_progress, saved_count, status_box,
            ],
        )

        def on_save(sentences, position, next_idx, audio_path):
            if not sentences or position >= len(sentences):
                return (sentences, position, next_idx, "", "",
                        "No batch generated yet", str(next_idx - 1),
                        "Generate a batch first.", None)
            if not audio_path:
                sentence, filename, progress = describe(sentences, position, next_idx)
                return (sentences, position, next_idx, sentence, filename, progress,
                        str(next_idx - 1), "Record audio before saving.", None)

            text = sentences[position]
            wav_path = save_pair(output_dir, next_idx, text, audio_path)
            new_position = position + 1
            new_next_idx = next_idx + 1
            sentence, filename, progress = describe(sentences, new_position, new_next_idx)
            status = f"Saved {wav_path.name}"
            return (sentences, new_position, new_next_idx, sentence, filename, progress,
                    str(new_next_idx - 1), status, None)

        save_btn.click(
            on_save,
            inputs=[sentences_state, position_state, next_idx_state, audio_in],
            outputs=[
                sentences_state, position_state, next_idx_state,
                sentence_box, next_file_box, batch_progress, saved_count, status_box, audio_in,
            ],
        )

        def on_skip(sentences, position, next_idx):
            new_position = position + 1
            sentence, filename, progress = describe(sentences, new_position, next_idx)
            return (sentences, new_position, sentence, filename, progress,
                    str(next_idx - 1), "Skipped.", None)

        skip_btn.click(
            on_skip,
            inputs=[sentences_state, position_state, next_idx_state],
            outputs=[
                sentences_state, position_state,
                sentence_box, next_file_box, batch_progress, saved_count, status_box, audio_in,
            ],
        )

    return demo


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--batch-size", type=int, default=20)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--port", type=int, default=7861)
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    demo = build_app(args.model, args.batch_size, output_dir)
    print(f"Recording studio: http://localhost:{args.port}")
    demo.launch(server_port=args.port, share=False)


if __name__ == "__main__":
    main()
